### ISSUE TITLE
Not pulling the latest version of Thunderbird

### ISSUE THREAD

**Issue by yllekz** [ich777/docker-thunderbird#1]
I just deployed this container with the "latest" tag. Works great, except the version of Thunderbird it is pulling is not the latest one. It is pulling 60.9.0 while the latest version is 78.5.1. Is something wrong with the version detection?

**Comment by ich777** [comment]
Thanks for reporting this!
Are we talking about the x86_64 build or the arm versions?
Have you restarted the container already?

**Comment by yllekz** [comment]
No problem. This is the arm variant (Raspberry Pi 4B), via the "latest" tag. Yeah I have restarted it a few times today.

**Comment by ich777** [comment]
That's because there are no official builds for the arm version available only the LTS versions in the debian repo...
The "latest" variable is sadly enough only usable for the amd64 build.

**Comment by ich777** [comment]
So can this issue now be closed?

**Comment by yllekz** [comment]
Thanks, hmm that's interesting, and disappointing. Not something you can control though. Yeah we can close this. Thanks!
