### ISSUE TITLE
Failed to execute child process “update-desktop-database”

### ISSUE THREAD

**Issue by sam-k-taylor** [ich777/docker-thunderbird#12]
Getting a few errors when starting the container.

```
---Ensuring UID: 1000 matches user---
usermod: no changes
---Ensuring GID: 1000 matches user---
usermod: no changes
---Setting umask to 000---
---Checking for optional scripts---
---No optional script found, continuing---
---Checking configuration for noVNC---
Nothing to do, noVNC resizing set to default
Nothing to do, noVNC qaulity set to default
Nothing to do, noVNC compression set to default
---Taking ownership of data...---
---Starting...---
---Preparing Server---
---Resolution check---
---Checking for old logfiles---
---Checking for old display lock files---
---Starting TurboVNC server---
---Starting Fluxbox---
---Starting noVNC server---
WebSocket server settings:
  - Listen on :8080
  - Web server. Web root: /usr/share/novnc
  - No SSL/TLS support (no cert file)
  - Backgrounding (daemon)
---Starting Thunderbird---
[GFX1-]: glxtest: libpci missing
[Parent 90, Main Thread] WARNING: Failed to execute child process “update-desktop-database” (No such file or directory): 'glib warning', file /builds/worker/checkouts/gecko/toolkit/xre/nsSigHandlers.cpp:167

(thunderbird:90): GLib-GIO-WARNING **: 12:25:36.222: Failed to execute child process “update-desktop-database” (No such file or directory)

```

**Comment by ich777** [comment]
@sam-k-taylor these are `WARNINGS` not `ERROR`s, that's actually caused because I only ship the bare minimum with the container without a "real" desktop environment.

`libpci` is not really needed to run Thunderbird <- this library is only used for testing if a suitable 3D accelerator is installed.
The second is because some other things for the desktop environment are missing.

I could of course hide these messages but I think it's better to not hide them.

Nothing to worry about and the container is just working fine even with these two warnings, I use it on a daily basis as my main Mail client.
Do you have any issues with the container, it should be reachable by using this address: `http://IP:PORT/vnc.html?autoconnect=true`

**Comment by sam-k-taylor** [comment]
that being that it is its not working, when i goto the address the page loads for ages and eventually times out, not idea where to look for info on why if its not in the docker log

**Comment by ich777** [comment]
> that being that it is its not working, when i goto the address the page loads for ages and eventually times out, not idea where to look for info on why if its not in the docker log

Can you please share your `docker run` command?

**Comment by sam-k-taylor** [comment]
```
docker run --name Thunderbird -d \as
        -p 8080:8080 \
        --env 'THUNDERBIRD_V=latest' \
        --env 'THUNDERBIRD_LANG=en-US' \
        --env 'TURBOVNC_PARAMS=-securitytypes none' \
        --env 'CUSTOM_RES_W=1280' \
        --env 'CUSTOM_RES_H=768' \
        --env 'UID=1000' \
        --env 'GID=1000' \
        --env 'UMASK=000' \
        --env 'DATA_PERM=770' \
        --volume ~/.thunderbird-test:/thunderbird \
        ich777/thunderbird
```

**Comment by sam-k-taylor** [comment]
i am trying to access the interface from another machine if that makes a difference

**Comment by ich777** [comment]
> i am trying to access the interface from another machine if that makes a difference

Your `docker run` command seems fine to me, except for the `\as` part on the first line.

Are you sure that you don't have to create any additional firewall rules to let anyone other than `localhost` connect to the machine where the Thunderbird container is located at?

I can only tell that it is just working fine over here, I even have a few users on ARM machines who are using this container.
Can you maybe open up a terminal from the container and copy past the following:
```
apt-get update
apt-get -y install net-tools
```
After that please run: `netstat -tulpen` from inside the container and paste the output here.

**Comment by sam-k-taylor** [comment]
```
netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name    
tcp        0      0 0.0.0.0:5900            0.0.0.0:*               LISTEN      1000       176964     -                   
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1000       177237     -                   

```

**Comment by sam-k-taylor** [comment]
you know what, ignore me, working now `192.168.1.103` not `192.168.0.103` feel very dumb rn

**Comment by ich777** [comment]
So is everything now working?

**Comment by sam-k-taylor** [comment]
yeah, sorry to bother you

**Comment by ich777** [comment]
No worries, glad that everything is now working for you! I will close this issue, if you are experiencing other issues please feel free to open up a new issue... :)
