### ISSUE TITLE
vncpasswd: command not found

### ISSUE THREAD

**Issue by kapkinn** [ich777/docker-thunderbird#14]
Dear creator,

I do love the package, thank you for the work done.
To docker I'm an absolute newbie and am struggling to set the VNC password.
The Container Console (started from Portainer) does print the error "vncpasswd: command not found".
I'm using a raspberry pi with RASPIAN, Docker and Portainer. All does work fine but without password protection.

Sorry to report this as an issue, maybe or most probably this is my fault because of a lack of knowledge.

**Comment by ich777** [comment]
> I'm using a raspberry pi with RASPIAN, Docker and Portainer. All does work fine but without password protection.

Please post your `docker run` command?

**Comment by republicandaddy** [comment]
I'm having the same issue.  I host it inside a k3s cluster on raspberry pi 4Bs.  I access the console through portainer with the /bin/bash command.  I'm able to get to the console fine, but when I run the vncpasswd command it shows "bash: vncpasswd: command not found".

What am I doing wrong here?

**Comment by kapkinn** [comment]
> > I'm using a raspberry pi with RASPIAN, Docker and Portainer. All does work fine but without password protection.
> 
> Please post your `docker run` command?

Docker run has been copied from the code page here

**Comment by ich777** [comment]
The tutorial applies only to `x86_64` containers, I maintain not much `arm64` or `armhf` containers anymore nowadays.
ARM containers are using `x11vnc` instead of `TurboVNC`, I have to set up a small node and try it on my own how to set up a password, I can't remember it anymore.

I will get back to you in the next few days, currently a bit overwhelmed by real life.

**Comment by kapkinn** [comment]
Hej, great ich777. Many thx for your help, no hurry.

**Comment by ich777** [comment]
I've now updated the container, please pull the update first and then follow the instructions below:

To set a password do the following:

1. Open a terminal from the container (root)
2. Type in `su $USER`
3. Type in `x11vnc --storepasswd`
4. Enter your password and press `Enter` two times (please note, the password is limited to a max of 8 characters)
5. Say `y` and press `Enter`
6. Create a new environment variable in the container with the key: `X11VNC_PARAMS` and as value: `-usepw`

After you restart the container you should be asked for a password.
Please let me know if everything is working.

**Comment by kapkinn** [comment]
Hello,
does work perfect! Thx for the change and the description
:-)

**Comment by ich777** [comment]
Thank you, I'll close this issue, if you experience any other issues please feel free to open a new issue.
