### ISSUE TITLE
Empty --env 'TURBOVNC_PARAMS=' not allowed on Synology, guide needs to add "VNC" as a variable

### ISSUE THREAD

**Issue by mrglutton** [ich777/docker-thunderbird#15]
Hello, there is an error in manual. Empty --env 'TURBOVNC_PARAMS=' is not permitted in Synology docker any more, but the following setting works:

TURBOVNC_PARAMS= VNC

Can you maybe update the tutorial?

**Comment by ich777** [comment]
> Hello, there is an error in manual. Empty --env 'TURBOVNC_PARAMS=' is not permitted in Synology docker any more, but the following setting works:

Did it work before? If it did work before why does it not work anymore? I also don't think that this will work: `TURBOVNC_PARAMS= VNC`

Does it also work with: `TURBOVNC_PARAMS= ` (with a space at the end)?

BTW, I know that it works also with `TURBOVNC_PARAMS=-securititypes VNC` (see the documentation over [here](https://github.com/TurboVNC/turbovnc/blob/main/doc/auth.txt#L112)).

**Comment by mrglutton** [comment]
Sorry, I mistyped - "-securititypes VNC" is the correct setting I ommited that part. 

In Synology servers you can't set the parameters in text file, but they are listed in a table-like structure where no values can be left empty. I haven't tried with "space" value, I can try if you want. The container works fine if I use it on default setting, which is set automatically to "-securitytypes none".

**Comment by ich777** [comment]
Yes please, test if a space is allowed.

I think in the description from one of my containers I have a note about that because on Portainer a empty variable nor a space at the value from the variable is not allowed, but I can‘t remember which one it is (maybe Firefox or Chrome).

**Comment by mrglutton** [comment]
Hello, I tested it and I can confirm that it works as intended with the space character as a variable value, meaning it asks for password.

I did return -securitytypes VNC as the variable value though.

**Comment by ich777** [comment]
I will update the README.md ASAP, I will close this PR for now. Thank you for the report!

**Comment by mrglutton** [comment]
Thank you. I appreciate that you replied so fast and fixed the issue. :-)

And thanks a lot for making the TB Docker, it is really useful for me!
