### ISSUE TITLE
chmod: Operation not permitted

### ISSUE THREAD

**Issue by republicandaddy** [ich777/docker-thunderbird#17]
Hi there...I doubt this is your build, but I can't figure out what the heck I'm doing wrong....

So, I'm spinning this up as a pod on a k3s cluster.  It's a mixed cluster of Raspberry Pi 4B's and 2 amd64 based machines in a k3s cluster.  That said, it worked fine a few months ago, but I blew it away to try out some other options...didn't like them, so I'm back trying to get this back up and running. 

Each time I try, the log file shows this:

2023-06-26T15:11:53.908303252-07:00 chmod: changing permissions of '/thunderbird/rnpkeys': Operation not permitted
2023-06-26T15:11:53.908428311-07:00 chmod: changing permissions of '/thunderbird/defaults': Operation not permitted
2023-06-26T15:11:53.908697145-07:00 chmod: changing permissions of '/thunderbird/defaults/messenger': Operation not permitted
2023-06-26T15:11:53.909028815-07:00 chmod: changing permissions of '/thunderbird/defaults/messenger/mailViews.dat': Operation not permitted
2023-06-26T15:11:53.909151918-07:00 chmod: changing permissions of '/thunderbird/defaults/pref': Operation not permitted
2023-06-26T15:11:53.909504850-07:00 chmod: changing permissions of '/thunderbird/defaults/pref/channel-prefs.js': Operation not permitted
2023-06-26T15:11:53.909725696-07:00 chmod: changing permissions of '/thunderbird/plugin-container': Operation not permitted
2023-06-26T15:11:53.910035338-07:00 chmod: changing permissions of '/thunderbird/precomplete': Operation not permitted
2023-06-26T15:11:53.910233444-07:00 chmod: changing permissions of '/thunderbird/profile': Operation not permitted
2023-06-26T15:11:53.910568951-07:00 chmod: changing permissions of '/thunderbird/.vnc': Operation not permitted
2023-06-26T15:11:53.910977719-07:00 chmod: changing permissions of '/thunderbird/.thunderbird': Operation not permitted
2023-06-26T15:11:53.911300224-07:00 chmod: changing permissions of '/thunderbird/.thunderbird/Crash Reports': Operation not permitted
2023-06-26T15:11:53.911659737-07:00 chmod: changing permissions of '/thunderbird/.thunderbird/Crash Reports/events': Operation not permitted
2023-06-26T15:11:53.912174742-07:00 chmod: changing permissions of '/thunderbird/.thunderbird/Crash Reports/InstallTime20220906224751': Operation not permitted
2023-06-26T15:11:53.912410327-07:00 chmod: changing permissions of '/thunderbird/.thunderbird/Pending Pings': Operation not permitted
2023-06-26T15:11:53.912689300-07:00 chmod: changing permissions of '/thunderbird/.cache': Operation not permitted
2023-06-26T15:11:53.914735410-07:00 ---Starting TurboVNC server---
2023-06-26T15:11:55.936009356-07:00 ---Starting Fluxbox---
2023-06-26T15:11:55.946541439-07:00 Fluxbox crashed with exit code 1.  Respawning..
2023-06-26T15:11:56.955644056-07:00 Fluxbox crashed with exit code 1.  Respawning..
2023-06-26T15:11:57.937535977-07:00 ---Starting noVNC server---
2023-06-26T15:11:57.962887120-07:00 Fluxbox crashed with exit code 1.  Respawning..
2023-06-26T15:11:58.070788407-07:00 WebSocket server settings:
2023-06-26T15:11:58.070819360-07:00   - Listen on :8080
2023-06-26T15:11:58.070835743-07:00   - Web server. Web root: /usr/share/novnc
2023-06-26T15:11:58.070938416-07:00   - No SSL/TLS support (no cert file)
2023-06-26T15:11:58.070957866-07:00   - Backgrounding (daemon)
2023-06-26T15:11:58.969833458-07:00 Fluxbox crashed with exit code 1.  Respawning..
2023-06-26T15:11:59.976335301-07:00 Fluxbox crashed with exit code 1.  Respawning..
2023-06-26T15:12:00.073923724-07:00 ---Starting Thunderbird---
2023-06-26T15:12:00.105588505-07:00 Error: cannot open display: :99

Now, I suspect the later part of the issues are caused by the pod's inability to change the permissions on the various folders.

The primary storage is an nfs volume on a Synology NAS.  I gave the IPs in the cluster all full access to the parent folder that holds the data folder and mapped them to admin, so they should have zero issues making changes to ownership.

Here's my setup file in yaml form:

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    io.portainer.kubernetes.application.note: ""
  creationTimestamp: 2023-06-26T21:46:33Z
  generation: 6
  labels:
    io.portainer.kubernetes.application.name: thunderbird
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: thunderbird
  name: thunderbird
  namespace: thunderbird
  uid: 6ee121b6-04a7-4bfe-844b-1f6a45d89b7a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: thunderbird
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: thunderbird
        io.portainer.kubernetes.application.name: thunderbird
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
              weight: 1
      containers:
        - env:
            - name: DATA_DIR
              value: /thunderbird
            - name: THUNDERBIRD_V
              value: latest
            - name: THUNDERBIRD_LANG
              value: en-US
            - name: CUSTOM_RES_W
              value: "1920"
            - name: CUSTOM_RES_H
              value: "1080"
            - name: DATA_PERM
              value: "770"
            - name: TURBOVNC_PARAMS
              value: -securitytypes none
            - name: CUSTOM_DEPTH
              value: "16"
            - name: GID
              value: "101"
            - name: UID
              value: "1032"
            - name: UMASK
              value: "000"
          image: docker.io/ich777/thunderbird:latest
          imagePullPolicy: Always
          name: thunderbird
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /thunderbird
              name: thunderbird-0f7679bc-6a8a-4695-b846-634505896fd0
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: registry-2
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: thunderbird-0f7679bc-6a8a-4695-b846-634505896fd0
          persistentVolumeClaim:
            claimName: thunderbird-0f7679bc-6a8a-4695-b846-634505896fd0
status:
  conditions:
    - lastTransitionTime: 2023-06-26T21:46:33Z
      lastUpdateTime: 2023-06-26T21:46:33Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: 2023-06-26T21:46:33Z
      lastUpdateTime: 2023-06-26T22:05:23Z
      message: ReplicaSet "thunderbird-695c6f444" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 6
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2023-06-26T21:46:32Z
  labels:
    io.portainer.kubernetes.application.name: thunderbird
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: thunderbird
  name: thunderbird
  namespace: thunderbird
  uid: a56aa9cb-235e-4b9e-b935-e90bb7b54b1d
spec:
  clusterIP: 10.43.12.158
  clusterIPs:
    - 10.43.12.158
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: port-0
      nodePort: 30080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: thunderbird
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

This is driving me crazy, so any help you can offer would be apprecaited.

**Comment by ich777** [comment]
@republicandaddy are you sure that the UID and GID can write to the directory that you've specified to write into?

This is most likely cause because the user doesn't have permission to change the permissions on the main data directory (this is done on each start from the container).

**Comment by republicandaddy** [comment]
That user is part of the admin group.  It's odd, I've changed the permissions for the admin group to allow full control, but after I start the container the permissions for changing ownership are revoked.

I'm going to try adding the user alone, rather than the group and see if that changes anything.

When you say "main directory"  are you referring to /thunderbird, or it's parent directory?

**Comment by republicandaddy** [comment]
Ok, so I couldn't seem to get past this issue.  While I work on figuring out what's going on with the permissions, I ended up adding UID 1032 to the parent folder as a full control user (and applied it to all child objects) rather than just the admin group the user belongs to.  This appears to fix the issue.  The container still throws the chown errors about permission denied, but since the folder gives that user proper rights from outside the container, I was able to get the container up and running...all appears to be working now.

Granted, this is a Band-Aid fix for now....

I'll continue to test this to find where I went wrong and post my solution here when I find it.

**Comment by ich777** [comment]
This is really strange... Do you use the container on Kubernetes (TBH I'm not that familiar with Kubernetes)?
I can only tell you that it works fine if you use bare `docker` and I've had only a few users with issues also related to the permissions but there the permissions on the host directory where set incorrectly.

I would also really like to fix that so that this can maybe help other people.

Oh, sorry I've saw that I didn't answered this question:

> When you say "main directory" are you referring to /thunderbird, or it's parent directory?

I've meant the directory that you've bound on the host, but I think in your case you are using volumes correct?

The `chown` and `chmod` inside the container is running as `root` on startup and tries to ensure that the permissions for the directories are set correctly, I don't know why this is failing but as said above this could be because of Kubernetes (which I'm not familiar with) or the volume mount.

Thanks for reporting this BTW. Really appreciate it!

**Comment by republicandaddy** [comment]
Still working on what's going on in kubernetes (I use k3s), but in the mean time, adding the user instead of the user's group as owner of the parent folder and passing that to all subfolders and files did the trick.  It still throws the CHMOD error, but since the permissions are set by the NFS host, it doesn't matter.  So that's a good workaround for now.

**Comment by republicandaddy** [comment]
> > When you say "main directory" are you referring to /thunderbird, or it's parent directory?
> 
> I've meant the directory that you've bound on the host, but I think in your case you are using volumes correct?


Sorry for the late reply, but yes, I mean the /thunderbird directory.

I haven't been able to test this much farther, but at least for now, the fix is to change the ownership of the folder on the host and all subfolders/files to inherit those permissions to the UID being used on the setup.  This doesn't stop the error from popping up during the install, but after all is said and done, it works as though the error didn't exist.  It runs BEAUTIFULLY by doing this too.

I had this setup once before in my k3s cluster on an older version and it worked....although it was super sluggish.  Now it's lightening fast and working VERY well.  Even better than I expected. 

So, with the one error regarding chown being the exception it works very well in a Kubernetes environment as long as you use the work around I stated above.

Unfortunately, I don't really know where else to go to figure out why it throws the error even when that UID has full permissions to chown on the host machine.  

Oh, and yes, I'm using volume mounts on the cluster machines to connect to the nfs4 volume on the host (which happens to be a Synology DS box). 

That does give me another idea though.  The next couple weeks are going to be killer for me at work, but I'll try to get to test this further by trying to mount the volume on a standard Linux box with nfs.  It could be the way Synology handles permissions through their GUI that is causing the problem.
