### ISSUE TITLE
Raspberry Pi: exec format error with latest image

### ISSUE THREAD

**Issue by yllekz** [ich777/docker-thunderbird#2]
Hello, with the latest version of the image I am suddenly getting an "exec format error" when updating the container on my Pi. Did something change?

**Comment by ich777** [comment]
@yllekz actually yes, can you give me one or two days to fix this?
Actually I depricated the ARM versions in my container maintainance phase because the last pull was about 6 months ago.
What version are you using? 64bit or 32bit, or better speaking which image does you run on your Raspberry Pi?

**Comment by yllekz** [comment]
Sure thing. Oh interesting, my box has been pulling the latest image more recently than that via Watchtower. I'm running the 32 bit version on my Pi right now.

**Comment by ich777** [comment]
@yllekz Hi, updated the images, the bad news is that armhf (armv7) I can only build a image for Buster and not for Bullseye, but it should work now again. Please try to pull it again and report back. :)

**Comment by yllekz** [comment]
Thanks! That got it back up and running. I'm running Buster so that's no problem for me.
