### ISSUE TITLE
vnc_auto.html

### ISSUE THREAD

**Issue by MRobi1** [ich777/docker-thunderbird#3]
Just set this up today to test it out. Looks like it will suit my needs perfectly.

When I navigate to http://[SERVERIP]:[PORT]/vnc_auto.html I get a 404 error.
If I drop the /vnc_auto.html I get a directory listing and in it I see a vnc.html
This puts me in without issues.

I'm assuming vnc_auto.html should automatically connect through the vnc server without having to hit the connect button in vnc.html?

**Comment by ich777** [comment]
@MRobi1 sorry for the inconvenience... :/

I updated the noVNC version a while back and forgot to change the link, the right one is:
`http://[SERVERIP]:[PORT]/vnc.html?autoconnect=true`

Please report back if everything is working with this URL, will change it in the README.md too.

**Comment by MRobi1** [comment]
That one works perfect! Thank you very much
