### ISSUE TITLE
Support Chinese language

### ISSUE THREAD

**Issue by yanickxia** [ich777/docker-thunderbird#5]
current installed, chinese not show
![image](https://user-images.githubusercontent.com/6848593/148483539-ad649b44-6c0b-46b9-96a4-e64579506b3f.png)

**Comment by ich777** [comment]
@yanickxia Images for `arm64`, `armv7` and `amd64` are now rebuilt, thank you!

**Comment by yanickxia** [comment]
> @yanickxia Images for `arm64`, `armv7` and `amd64` are now rebuilt, thank you!

A little work ,
Thanks for your work. I use this docker image for my calendars and mail.  This wonderful image.
